[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express", "pg", "cors", "dotenv", "zod"]
  node_bundler = "esbuild"
  included_files = ["node_modules/**"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
